name: Google Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Google Test Frmra
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/build;sh build_google_test.sh

    - name: Build Project
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/build;sh build.sh

    - name: Build Google Test
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/build;bash build_test.sh

    - name: Running
      # Build your program with the given configuration
      run: cd ${{github.workspace}};bash ./build/googleTest/running_unit_test.sh
      

