name: Google Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Google Test Frmra
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/build;sh build_google_test.sh

    - name: Build Google Test
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/build;sh build_test.sh

    # - name: Running
    #   run: sh ${{github.workspace}}/cassel/start.sh
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      

